(ns com.fulcrologic.statecharts.invocation.statechart
  "Support for invoking other statecharts. This support can be added by adding it to the
   env's `::sc/invocation-processors`. An invoke element can specify it wants to
   run another statechart by specifying the type as :statechart, ::sc/chart, or the official w3 URL for scxml.

   The `src` attribute of the `invoke` element must be the name of a machine that is in the
   statechart registry (in env as ::sc/statechart-registry).
   "
  (:require
    [clojure.string :as str]
    [com.fulcrologic.statecharts :as sc]
    [com.fulcrologic.statecharts.environment :as env]
    [com.fulcrologic.statecharts.protocols :as sp]
    [promesa.core :as p]
    [taoensso.timbre :as log]))

(defn- parent-hook-key?
  "Any `::sc/` key whose name ends with `-hooks` OR whose name is the
   event queue's save-attempted? marker is parent-session bookkeeping
   that must not leak into a child env. Pattern-based so a future hook
   (e.g. `::sc/on-delete-hooks`, `::sc/pre-save-hooks`) is stripped
   automatically without an explicit denylist update."
  [k]
  (and (keyword? k)
       (= (namespace k) (namespace ::sc/placeholder))
       (let [n (name k)]
         (or (str/ends-with? n "-hooks")
             (= n "save-attempted?")))))

(defn strip-parent-hooks
  "Remove every `::sc/*-hooks` key (and the event queue's
   `::sc/save-attempted?` signal) from `env`. The child save must not
   trigger parent-session bookkeeping."
  [env]
  (reduce-kv (fn [acc k v]
               (if (parent-hook-key? k)
                 acc
                 (assoc acc k v)))
             {}
             env))

(defn- resolve-child-session-id
  "Choose the child session-id for an invocation.

   When the user explicitly provided `:id` on the invoke element
   (`explicit-id?` true), the invokeid is the user's chosen session-id
   and we use it directly — required so the documented `:child-session-id`
   option in Fulcro routing still addresses the child at the expected id.

   Otherwise the invokeid was auto-generated by the algorithm
   (`<parent-state-id>.<uuid>`) and we scope to the parent session to
   avoid collisions across parent sessions that happen to pick the same
   auto-generated id."
  [source-session-id invokeid explicit-id?]
  (if explicit-id?
    (str invokeid)
    (str source-session-id "." (str invokeid))))

(defn- locate-child-session-id
  "At stop-invocation! / forward-event! time, `explicit-id?` may or may
   not be threaded through by callers. Probe the working-memory store to
   find whichever form was actually saved (prefer scoped, fall back to
   bare)."
  [env working-memory-store source-session-id invokeid explicit-id?]
  (let [scoped-id (str source-session-id "." (str invokeid))
        bare-id   (str invokeid)]
    (cond
      ;; When the caller knows the id was explicit, go straight to bare.
      explicit-id? bare-id
      ;; Otherwise probe scoped first (the normal case), then bare (for
      ;; backward compat with routers that don't yet thread :explicit-id?).
      (and working-memory-store (sp/get-working-memory working-memory-store env scoped-id))
      scoped-id

      (and working-memory-store (sp/get-working-memory working-memory-store env bare-id))
      bare-id

      :else scoped-id)))

(defrecord StatechartInvocationProcessor [active-invocations]
  sp/InvocationProcessor
  (supports-invocation-type? [this typ]
    (or
      (and (string? typ) (str/starts-with? (str/lower-case typ) "http://www.w3.org/tr/scxml"))
      (= typ :statechart)
      (= typ ::sc/chart)))
  ;; Returns: false if chart not found, true (sync) or Promise<true> (async) on success
  (start-invocation! [this {::sc/keys [event-queue processor statechart-registry working-memory-store]
                            :as       env} {:keys [invokeid src params explicit-id?]}]
    (log/debug "Start invocation" invokeid src params (when explicit-id? "(explicit-id)"))
    (let [source-session-id (env/session-id env)
          child-session-id  (resolve-child-session-id source-session-id invokeid explicit-id?)
          statechart        (sp/get-statechart statechart-registry src)]
      (if-not statechart
        (do
          (log/error "Invocation failed. No statechart found for src:" src)
          (sp/send! event-queue env {:target            source-session-id
                                     :sendid            child-session-id
                                     :source-session-id child-session-id
                                     :event             :error.platform
                                     :data              {:message "Could not invoke child chart. Not registered."
                                                         :target  src}})
          false)
        ;; Strip ALL parent-event side-effect hooks from env before
        ;; starting the child. The JDBC event queue installs
        ;; `::sc/on-save-hooks` / `::sc/save-attempted?` so the parent
        ;; event is ACKed atomically with the parent WM save — but the
        ;; child's first save uses this same env, which would fire the
        ;; parent's hook prematurely and mark the parent event processed
        ;; before the parent itself has saved. A later parent save
        ;; failure (e.g. optimistic-lock conflict) then silently loses
        ;; the event.
        ;;
        ;; Pattern-based sweep (not an explicit denylist): any `::sc/`
        ;; key whose name ends with `-hooks` OR whose name is
        ;; `save-attempted?` is parent-session bookkeeping. Adding a new
        ;; hook to the event queue does NOT require remembering to
        ;; update this dissoc — the sweep catches it automatically.
        (let [child-env (strip-parent-hooks env)
              result    (sp/start! processor child-env src {::sc/invocation-data         (or params {})
                                                             ::sc/session-id              child-session-id
                                                             ::sc/parent-session-id       source-session-id
                                                             :org.w3.scxml.event/invokeid invokeid})
              save!     (fn [wmem]
                          (sp/save-working-memory! working-memory-store child-env child-session-id wmem)
                          true)]
          ;; Block until the child save commits, whether sync or async.
          ;; Returning a raw Promise<true> to the SCXML processor lets
          ;; the caller's subsequent parent save commit — and therefore
          ;; ACK the parent event — before the child has been persisted.
          ;; If the async save then rejects, the parent event is already
          ;; ACKed, the child was never written, and the next poll
          ;; won't retry. `@(p/then ...)` waits for the chained save
          ;; before `start-invocation!` returns `true`/`false`.
          (if (p/promise? result)
            @(p/then result save!)
            (save! result))))))
  (stop-invocation! [this {::sc/keys [event-queue processor working-memory-store] :as env} {:keys [invokeid explicit-id?] :as data}]
    (log/debug "Stop invocation" invokeid)
    (let [source-session-id (env/session-id env)
          child-session-id  (locate-child-session-id env working-memory-store source-session-id invokeid explicit-id?)
          wmem              (sp/get-working-memory working-memory-store env child-session-id)]
      (when wmem
        (let [result (sp/exit! processor env wmem true)
              clean! (fn [_] (sp/delete-working-memory! working-memory-store env child-session-id))]
          (if (p/promise? result)
            (p/then result clean!)
            (clean! result))))
      true))
  (forward-event! [this {::sc/keys [event-queue working-memory-store] :as env} {:keys [type invokeid event explicit-id?]}]
    (log/debug "Forward event " invokeid event)
    (let [source-session-id (env/session-id env)
          child-session-id  (locate-child-session-id env working-memory-store source-session-id invokeid explicit-id?)]
      (when event-queue
        (log/debug "sending event on event queue to" child-session-id)
        (sp/send! event-queue env {:target            child-session-id
                                   :type              (or type ::sc/chart)
                                   :sendid            child-session-id
                                   :source-session-id source-session-id
                                   :data              (or (:data event) {})
                                   :event             (:name event)}))
      true)))

(defn new-invocation-processor
  "Create an invocation processor that can be used with a statechart to start other statecharts."
  []
  (->StatechartInvocationProcessor (atom {})))
